### ISSUE TITLE
Transform 'сегодня' and 'завтра' to valid dates

### ISSUE THREAD

**Issue by polina-popova** [tolstoyevsky/hubot-viva-las-vegas#105]
![Selection_170](https://user-images.githubusercontent.com/42995454/56043764-962aec00-5d46-11e9-83a6-fa7e1d9a45e4.png)

**Comment by eugulixes** [comment]
Should have been closed by https://github.com/tolstoyevsky/hubot-viva-las-vegas/pull/104/commits/275b3bdfadcfc24a309ffa1b13a36e1a38edf084.
