### ISSUE TITLE
Fix days counting in reminders

### ISSUE THREAD

**Issue by polina-popova** [tolstoyevsky/hubot-viva-las-vegas#106]
If you form leave request for today bot will send reminder that leave request starts in one day.
![Selection_172](https://user-images.githubusercontent.com/42995454/56048797-e909a100-5d50-11e9-867b-88595403c7cb.png)

**Comment by eugulixes** [comment]
Should have been closed by https://github.com/tolstoyevsky/hubot-viva-las-vegas/pull/104/commits/b1f08cfe617fb2ab55f5bcb678bb3b41b0db3ec6.
