### ISSUE TITLE
Date validation fails

### ISSUE THREAD

**Issue by ukhryab** [tolstoyevsky/hubot-viva-las-vegas#11]
The script stucks after receiving such dates as `32.09` or `28.09.2018`, leaving no message to the user.

**Comment by eugulixes** [comment]
This is the feature of the regex we are using: `/((0?[1-9]|[12][0-9]|3[01])\.(0?[1-9]|1[0-2]))$/`. So, there can be not more than 31 days even in the fattest month. So, do we have to consider `100.100` as not valid date?
Speaking about `28.09.2018`. The bot says that it waits for `dd.mm`. Is there any a reason to give him something else and wait for some feedback from him? No, I guess.

**Comment by ukhryab** [comment]
Ok, I agree with you, that it is not a bug. But I believe, it would be a much better UX, if user gets any clarifying response message, just as `Wrong date`, instead of receiving nothing and frustrating - have I done something wrong or it's just the script hung up? You know, users in general are not perfect and can make typos in writing and not notice bot's tips at all.
